package Vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 * Ventana Principal del Sistema (Dashboard). Actúa como contenedor MDI
 * (Multiple Document Interface) utilizando un JDesktopPane para gestionar todas
 * las ventanas internas (JInternalFrame) del sistema SCTA.
 *
 * * @author lsuar
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Panel de escritorio estático que permite a otras clases acceder y añadir
     * marcos internos al menú principal.
     */
    public static JDesktopPane jDesktopPane_menu;

    /**
     * Constructor de la clase FrmMenu. Configura la interfaz de usuario
     * maximizada, el título del sistema e inicializa el contenedor de
     * escritorio adaptado a la resolución de pantalla.
     */
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(FrmMenu.MAXIMIZED_BOTH); // Inicia maximizado
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas - SCTA");
        this.setLayout(null);

        // Configuración dinámica del JDesktopPane según el tamaño del monitor
        jDesktopPane_menu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        FrmMenu.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_gestionarUsuario = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_consultadeproductos = new javax.swing.JMenuItem();
        jMenuItem_registrodemercancias = new javax.swing.JMenuItem();
        jMenuItem_configuraciondeproductos = new javax.swing.JMenuItem();
        jMenuItem_ajustedeinventario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_nuevacategoria = new javax.swing.JMenuItem();
        jMenuItem_gestionarcategorias = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem_nuevaventa = new javax.swing.JMenuItem();
        jMenuItem_gestionarventas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_gestiondeprecios = new javax.swing.JMenuItem();
        jMenuItem_catalogodeproveedores = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_reportesclientes = new javax.swing.JMenuItem();
        jMenuItem_reportescategorias = new javax.swing.JMenuItem();
        jMenuItem_reportesproductos = new javax.swing.JMenuItem();
        jMenuItem_reportesventas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_nuevocliente = new javax.swing.JMenuItem();
        jMenuItem_gestionarclientes = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_cerrarsesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jMenu6.setText("Usuario");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_gestionarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jMenuItem_gestionarUsuario.setText("Cambiar Credenciales");
        jMenuItem_gestionarUsuario.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_gestionarUsuario);

        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/password.png"))); // NOI18N
        jMenuItem5.setText("Cambiar Pregunta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        jMenu1.setText("Inventarios");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_consultadeproductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_consultadeproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        jMenuItem_consultadeproductos.setText("Consulta de Productos");
        jMenuItem_consultadeproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_consultadeproductosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_consultadeproductos);

        jMenuItem_registrodemercancias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_registrodemercancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-producto.png"))); // NOI18N
        jMenuItem_registrodemercancias.setText("Registro de Productos");
        jMenuItem_registrodemercancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_registrodemercanciasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_registrodemercancias);

        jMenuItem_configuraciondeproductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_configuraciondeproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jMenuItem_configuraciondeproductos.setText("Configuración de Productos");
        jMenuItem_configuraciondeproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_configuraciondeproductosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_configuraciondeproductos);

        jMenuItem_ajustedeinventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_ajustedeinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jMenuItem_ajustedeinventario.setText("Entrada de Productos");
        jMenuItem_ajustedeinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ajustedeinventarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_ajustedeinventario);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jMenuItem2.setText("Ajuste de Inventario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        jMenu7.setText("Categorías");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevacategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_nuevacategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jMenuItem_nuevacategoria.setText("Nueva Categoría");
        jMenuItem_nuevacategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevacategoriaActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_nuevacategoria);

        jMenuItem_gestionarcategorias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarcategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        jMenuItem_gestionarcategorias.setText("Gestionar Categorías");
        jMenuItem_gestionarcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarcategoriasActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_gestionarcategorias);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial1.png"))); // NOI18N
        jMenuItem4.setText("Reglas de Descuento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuBar1.add(jMenu7);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        jMenu9.setText("Punto de Venta");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_nuevaventa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_nuevaventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jMenuItem_nuevaventa.setText("Nueva Venta");
        jMenu9.add(jMenuItem_nuevaventa);

        jMenuItem_gestionarventas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        jMenuItem_gestionarventas.setText("Gestionar Ventas");
        jMenu9.add(jMenuItem_gestionarventas);

        jMenuBar1.add(jMenu9);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenu2.setText("Precios");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_gestiondeprecios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestiondeprecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenuItem_gestiondeprecios.setText("Gestión de Precios");
        jMenu2.add(jMenuItem_gestiondeprecios);

        jMenuItem_catalogodeproveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_catalogodeproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenuItem_catalogodeproveedores.setText("Catálogo de Proveedores");
        jMenu2.add(jMenuItem_catalogodeproveedores);

        jMenuBar1.add(jMenu2);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenu8.setText("Reportes");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_reportesclientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportesclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportesclientes.setText("Reportes de Clientes");
        jMenu8.add(jMenuItem_reportesclientes);

        jMenuItem_reportescategorias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportescategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportescategorias.setText("Reportes de Categorias");
        jMenu8.add(jMenuItem_reportescategorias);

        jMenuItem_reportesproductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportesproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportesproductos.setText("Reportes de Productos");
        jMenu8.add(jMenuItem_reportesproductos);

        jMenuItem_reportesventas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportesventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportesventas.setText("Reportes de Ventas");
        jMenu8.add(jMenuItem_reportesventas);

        jMenuBar1.add(jMenu8);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        jMenu4.setText("Fidelización");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevocliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_nuevocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-cliente.png"))); // NOI18N
        jMenuItem_nuevocliente.setText("Nuevo Cliente");
        jMenuItem_nuevocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevoclienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_nuevocliente);

        jMenuItem_gestionarclientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        jMenuItem_gestionarclientes.setText("Gestionar Clientes");
        jMenuItem_gestionarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarclientesActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_gestionarclientes);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial1.png"))); // NOI18N
        jMenuItem3.setText("Consulta de Puntos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(175, 50));

        jMenuItem_cerrarsesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenuItem_cerrarsesion.setText("Cerrar Sesión");
        jMenuItem_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cerrarsesionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_cerrarsesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre la interfaz interna para el registro de nuevos clientes.
     */
    private void jMenuItem_nuevoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevoclienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem_nuevoclienteActionPerformed

    /**
     * Abre la interfaz interna para la creación de nuevas categorías de
     * productos.
     */
    private void jMenuItem_nuevacategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevacategoriaActionPerformed
        // TODO add your handling code here:

        InterCategoria intercategoria = new InterCategoria();
        jDesktopPane_menu.add(intercategoria);
        intercategoria.setVisible(true);


    }//GEN-LAST:event_jMenuItem_nuevacategoriaActionPerformed

    /**
     * Gestiona la apertura de la ventana de administración de categorías
     * existentes.
     */
    private void jMenuItem_gestionarcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarcategoriasActionPerformed
        // TODO add your handling code here:

        InterGestionarCategorias intergestionarcategorias = new InterGestionarCategorias();
        jDesktopPane_menu.add(intergestionarcategorias);
        intergestionarcategorias.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionarcategoriasActionPerformed

    /**
     * Abre el formulario de registro de nuevos productos al inventario.
     */
    private void jMenuItem_registrodemercanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_registrodemercanciasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem_registrodemercanciasActionPerformed

    /**
     * Permite visualizar el listado completo de productos registrados.
     */
    private void jMenuItem_consultadeproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_consultadeproductosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem_consultadeproductosActionPerformed

    /**
     * Abre la ventana de configuración avanzada de productos.
     */
    private void jMenuItem_configuraciondeproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_configuraciondeproductosActionPerformed
        // TODO add your handling code here:



    }//GEN-LAST:event_jMenuItem_configuraciondeproductosActionPerformed

    /**
     * Abre el módulo para el ajuste manual de stock en el inventario.
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:



    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * Abre el módulo específico para el registro de entradas de mercancía.
     */
    private void jMenuItem_ajustedeinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ajustedeinventarioActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem_ajustedeinventarioActionPerformed

    /**
     * Abre la interfaz de gestión y edición de clientes registrados.
     */
    private void jMenuItem_gestionarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarclientesActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem_gestionarclientesActionPerformed

    /**
     * Abre la consulta de puntos acumulados por clientes (Fidelización).
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * Configura los parámetros de reglas de descuento del sistema.
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        ConfiguracionReglasDescuento reglasDescuento = new ConfiguracionReglasDescuento();
        jDesktopPane_menu.add(reglasDescuento);
        reglasDescuento.setVisible(true);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * Abre la ventana de gestión de credenciales del usuario actual.
     */
    private void jMenuItem_gestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarUsuarioActionPerformed
        // TODO add your handling code here:

        InterGestionUsuario gestionusuario = new InterGestionUsuario();
        jDesktopPane_menu.add(gestionusuario);
        gestionusuario.setVisible(true);

    }//GEN-LAST:event_jMenuItem_gestionarUsuarioActionPerformed

    /**
     * Finaliza la sesión actual, cierra el menú principal y retorna a la
     * ventana de Login.
     */
    private void jMenuItem_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cerrarsesionActionPerformed
        // TODO add your handling code here:

        SCTALogin login = new SCTALogin();
        login.setVisible(true);

        this.dispose();

        JOptionPane.showMessageDialog(null, "Sesión Cerrada", "Sesión Cerrada", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItem_cerrarsesionActionPerformed

    /**
     * Abre el módulo para cambiar o gestionar la pregunta de seguridad del
     * administrador.
     */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        InterGestionPregunta gestionPregunta = new InterGestionPregunta();
        jDesktopPane_menu.add(gestionPregunta);
        gestionPregunta.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    /**
     * Método principal que lanza la aplicación en el hilo de eventos de AWT.
     *
     * @param args Argumentos de la línea de comandos.
     */
    public static void main(String args[]) {
        // ... (Configuración de Look and Feel y ejecución)
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem_ajustedeinventario;
    private javax.swing.JMenuItem jMenuItem_catalogodeproveedores;
    private javax.swing.JMenuItem jMenuItem_cerrarsesion;
    private javax.swing.JMenuItem jMenuItem_configuraciondeproductos;
    private javax.swing.JMenuItem jMenuItem_consultadeproductos;
    private javax.swing.JMenuItem jMenuItem_gestionarUsuario;
    private javax.swing.JMenuItem jMenuItem_gestionarcategorias;
    private javax.swing.JMenuItem jMenuItem_gestionarclientes;
    private javax.swing.JMenuItem jMenuItem_gestionarventas;
    private javax.swing.JMenuItem jMenuItem_gestiondeprecios;
    private javax.swing.JMenuItem jMenuItem_nuevacategoria;
    private javax.swing.JMenuItem jMenuItem_nuevaventa;
    private javax.swing.JMenuItem jMenuItem_nuevocliente;
    private javax.swing.JMenuItem jMenuItem_registrodemercancias;
    private javax.swing.JMenuItem jMenuItem_reportescategorias;
    private javax.swing.JMenuItem jMenuItem_reportesclientes;
    private javax.swing.JMenuItem jMenuItem_reportesproductos;
    private javax.swing.JMenuItem jMenuItem_reportesventas;
    // End of variables declaration//GEN-END:variables
}
